-- MySQL Script generated by MySQL Workbench
-- Wed May 12 12:20:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog` DEFAULT CHARACTER SET utf8 ;
USE `blog` ;

-- -----------------------------------------------------
-- Table `blog`.`usagers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`usagers` (
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `surnom_UNIQUE` (`username` ASC),
  PRIMARY KEY (`username`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Dumping data usagers - password: password123
-- -----------------------------------------------------

INSERT INTO `blog`.`usagers`(`username`, `password`, `prenom`, `nom`) VALUES
('Pier2208', '$2y$12$xtoBZ/13f.1P79QoB5vz7uP8DdKHXomQd3RVi7Jx1xVRooSRU9toO', 'Pierrick', 'Le Roy'),
('Paolo', '$2y$12$SqqBh0knXt31lraHwGJzsOGLlSliI7nA5orgSIFS2y6adPUMQNEfG', 'Paolo', 'Tono'),
('Jim', '$2y$12$TKEbfbWtM4Bbp9eFZCtGAOOC0bhI3HFdMGIa7Qvof5Po5KJ1MW3ne', 'Jim', 'Jarmush'),
('Sofia', '$2y$12$moZ0pUIdU9Fw6LIY64m9VOIhyPewTdQos/CvBhVRQfxqpOXDpQ/DG', 'Sofia', 'Coppola'),
('Gabriel', '$2y$12$ckN9ElbbO9xIy7isVYzFPOLSVOkU2.94VmDss2bRailZdAbtT03CO', 'Gabriel', 'Tremblay'),
('Sonia', '$2y$12$SbhFB/1K37lRdmlaNxYaruxKQOAWhOhKszp22s4/5SRhK61krH27i', 'Sonia', 'Lavergne'); 



-- -----------------------------------------------------
-- Table `blog`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog`.`articles` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(100) NOT NULL,
  `texte` LONGTEXT NOT NULL,
  `idAuteur` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `estRedigePar_idx` (`idAuteur` ASC),
  CONSTRAINT `estRedigePar`
    FOREIGN KEY (`idAuteur`)
    REFERENCES `blog`.`usagers` (`username`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Dumping data articles - Password: password123
-- -----------------------------------------------------

INSERT INTO `blog`.`articles`(`titre`, `texte`, `idAuteur`) VALUES
('echo park iceland freegan pour-over', 'Im baby hell of typewriter viral man bun hot chicken migas cliche 90s locavore art party swag.
 Raw denim polaroid echo park iceland freegan pour-over. Humblebrag yr meh shaman twee activated charcoal gentrify.
  Hashtag iceland subway tile banjo, pour-over live-edge locavore shabby chic crucifix succulents man bun vinyl coloring book blue bottle scenester.
   Cray prism pug intelligentsia kickstarter pop-up.', 'Pier2208'),
('Meditation af aesthetic unicorn', 'Synth everyday carry letterpress unicorn, banjo gochujang migas man braid austin typewriter mumblecore ennui salvia.
 Tbh pitchfork sriracha lomo try-hard, tumeric neutra. Meh adaptogen wayfarers, gochujang art party farm-to-table subway tile before they sold out health
  goth retro fashion axe.', 'Paolo'),
('Tote bag adaptogen taxidermy', 'umami aesthetic drinking vinegar meggings craft beer. Master cleanse brunch XOXO, swag cred kale chips tousled coloring 
book mixtape franzen blog biodiesel post-ironic vaporware. Health goth slow-carb craft beer lumbersexual locavore raw denim selfies pop-up tilde banjo.
 Migas gochujang cardigan DIY yr tumblr. Schlitz meditation biodiesel mixtape cred.', 'Sonia'),
('Hoodie austin succulents tattooed', 'Meditation af aesthetic unicorn messenger bag meh. La croix palo santo blue bottle swag. Air plant echo park man braid pork belly mixtape,
 edison bulb whatever vaporware. Health goth photo booth enamel pin kitsch whatever skateboard. Chartreuse tacos chambray raclette 
 iPhone you probably havent heard of them. Fingerstache plaid thundercats irony cold-pressed poutine.', 'Sonia'),
('coffee iPhone synth air plant vaporware', 'biodiesel post-ironic vaporware. Health goth slow-carb craft beer lumbersexual locavore raw denim selfies
 pop-up tilde banjo. Migas gochujang cardigan DIY yr tumblr. Schlitz meditation biodiesel mixtape cred. Sriracha woke tbh fashion axe.', 'Paolo'),
('Meh adaptogen wayfarers', 'Im baby hell of typewriter viral man bun hot chicken migas cliche 90s locavore art party swag.
 Raw denim polaroid echo park iceland freegan pour-over. Humblebrag yr meh shaman twee activated charcoal gentrify.
  Hashtag iceland subway tile banjo, pour-over live-edge locavore shabby chic crucifix succulents man bun vinyl coloring book blue bottle scenester.
   Cray prism pug intelligentsia kickstarter pop-up.', 'Paolo'),
('bicycle rights aesthetic', 'Sartorial pork belly messenger bag live-edge. Roof party street art fingerstache, bushwick live-edge glossier
 prism bespoke vaporware YOLO taxidermy messenger bag viral iceland. Pitchfork marfa sartorial vaporware, photo booth tacos sriracha chartreuse tousled
lyft ethical lumbersexual.', 'Gabriel'),
('edison bulb whatever', 'Im baby hell of typewriter viral man bun hot chicken migas cliche 90s locavore art party swag.
 Raw denim polaroid echo park iceland freegan pour-over. Humblebrag yr meh shaman twee activated charcoal gentrify.
  Hashtag iceland subway tile banjo, pour-over live-edge locavore shabby chic crucifix succulents man bun vinyl coloring book blue bottle scenester.
   Cray prism pug intelligentsia kickstarter pop-up.', 'Jim');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
